hooks/useInstagramAnalysis.tsx, hooks/usePrompts.tsx, lib/instagram/getDirectUrls.tsx, lib/instagram/getFormattedPostsComments.tsx, lib/instagram/getInstagramProfile.tsx, lib/instagram/getPostComment.tsx
Reverts recoupable/Recoup-Chat#245
=> myc 733 p0 instagram segment size incorrect

app/api/account/route.tsx, lib/supabase/getAccountByPhone.ts
- repo: https://github.com/recoupable/Recoup-Chat
- new endpoint: /api/account
- type: GET
- param: phone (string)
- query account_phone_numbers for any results including your phone number
- response:
- error- on error
- no results
- other error messages - data- on success - id - email
=> P1: /api/account - new endpoint

app/page.tsx, hooks/useFirstArtistRedirect.tsx
- actual: show CLICK HERE TO CREATE NEW ARTIST button
- required: redirect to `/funnels/wrapped`
- create a new hook to handle the redirect in hooks/useFirstArtistRedirect.tsx
=> `/` landing page - no artists

components/AutoPilot/AutoPilot.tsx, components/ui/skeleton.tsx
- actual: show CLICK HERE TO CREATE NEW ARTIST button when - logged out - no artist - etc
- required: show a skeleton of the AutoPilot page
- use shadcn/ui Skeleton component
- reference: components/AutoPilot/AutoPilot.tsx
=> AutoPilot Skeleton

.cursorrules
actual:
The project currently does not include a .cursorrules file. As a result, any functionality or configuration expected from this file is missing.
required:
Initialize a new .cursorrules file in the project. The file should include a basic configuration or placeholder rules that can be expanded in the future. If applicable, reference the existing documentation for the proper structure and expected content of a .cursorrules file, ensuring that the initial setup aligns with project standards.
=> P1: init .cursorrules file

.cursorrules, .gitignore, app/docs/account/constants.ts, app/docs/account/page.tsx
actual: missing docs for /api/account/socials
required: docs for /api/account/socials
reference existing docs in app/docs/base/page.tsx
=> P1: DOCS - account endpoints

app/docs/account/constants.ts, app/docs/account/page.tsx, app/docs/base/constants.ts, app/docs/base/page.tsx, app/docs/posts/constants.ts, app/docs/posts/page.tsx, app/docs/segment_report/constants.ts, app/docs/segment_report/page.tsx, components/docs/ResponseTable.tsx, types/Docs.tsx
actual:
There are currently no API docs for the /api/posts endpoint, which does not yet exist.
required:
Create API documentation for the /api/posts endpoint following the existing structure for API docs.
Parameters:
artist_account_id
Returns:
An array of Post[] from Supabase containing all posts from the artist across all social platforms.
Ensure that the docs clearly describe the endpoint’s purpose, parameter details, and response structure.
=> P1: Posts - API Doc

app/docs/fans/constants.ts, app/docs/fans/page.tsx
actual:
There are currently no API docs for the /api/fans endpoint, which does not yet exist.
required:
Create API documentation for the /api/fans endpoint following the existing structure for API docs.
Parameters:
artist_account_id
Returns:
An array of Social[] from Supabase containing all social profiles from the artist across all social platforms.
Ensure that the docs clearly describe the endpoint’s purpose, parameter details, and response structure.
=> P1: Fans - API Doc

app/layout.tsx, lib/consts.ts, lib/prompts/getSystemPrompt.ts
Current - System prompt is generic and has never been iterated on - causing responses to feel robotic and stale.
Expected - The system prompt is extensive and follows modern chat client prompt format (V0, Claude, ChatGPT, Cursor).
=> MYC-1387-p0-improve-system-prompt

components/Sidebar/RecentChats.tsx
Current: Recent chat shows all chats from all accounts artists
Expected: Recent chat only show selected artist chats
=> MYC-1507: Update RecentChats to only show selected artist chats

app/api/chat/vercel/route.ts, lib/errors/notifyError.ts, lib/telegram/sendErrorNotification.ts, lib/telegram/sendMessage.ts
Reverts recoupable/Recoup-Chat#516
=> Revert "Revert "Sweetmantech/myc 1580 p1 implement telegram error notifications for server chat""

components/VercelChat/ToolComponents.tsx, components/VercelChat/tools/CreateScheduledActionsSkeleton.tsx
A loading skeleton component was implemented for the `create_scheduled_actions` tool to enhance user experience during data fetching.
*   A new component, `components/VercelChat/tools/CreateScheduledActionsSkeleton.tsx`, was created.
*   This component provides a visual placeholder that mimics the structure of the `CreateScheduledActionsSuccess` component.
*   It includes animated skeleton elements for the header, two action cards with placeholder content, and metadata, using `animate-pulse` for a smooth loading effect.
*   Styling aligns with existing components, using muted slate colors to indicate a loading state.
*   The `components/VercelChat/ToolComponents.tsx` file was updated.
*   `CreateScheduledActionsSkeleton` was imported.
*   The `getToolCallComponent` function was modified …
=> Create loading skeleton for tool result UI

lib/apify/apifyPayloadSchema.ts, lib/apify/handleApifyWebhook.ts, lib/apify/handleInstagramProfileScraperResults.ts
The Apify webhook handling logic was refactored for improved modularity and clarity.
*   The schema in `lib/apify/apifyPayloadSchema.ts` was updated to explicitly define the `eventData` structure, including `actorId`, `actorTaskId` (optional), and `actorRunId`, enhancing type safety and adherence to Apify documentation.
*   A new module, `lib/apify/handleInstagramProfileScraperResults.ts`, was created. All specific logic for processing Instagram profile scraper results, previously embedded in `handleApifyWebhook.ts`, was migrated here. This includes dataset fetching, post saving, social profile updates, Arweave uploads, email notifications, and triggering comment scraping.
*   `lib/apify/handleApifyWebhook.ts` was refactored to act as a router. It now imports …
=> Create Instagram profile scraper results handler

lib/apify/handleApifyWebhook.ts, lib/apify/handleInstagramCommentsScraper.ts
A new file, `lib/apify/handleInstagramCommentsScraper.ts`, was created to specifically handle webhook data from the Instagram Comments Scraper actor (`SbK00X0JYCPblD2wp`).
This new handler:
*   Fetches the dataset using `getDataset`.
*   Processes the retrieved data, filtering for valid `InstagramComment` objects.
*   Extracts unique `postUrl` values and calculates the total number of comments.
*   Includes a TypeScript interface `InstagramComment` for type safety and data validation.
*   Returns processed comments along with metadata like `processedPostUrls` and `totalComments`, maintaining a consistent return structure with other handlers.
The main webhook router, `lib/apify/handleApifyWebhook.ts`, was updated to:
*   Import the new `handleInstagramCommentsScraper` function.
*   Add a …
=> Create Instagram comments scraper library

lib/supabase/error_logs/createErrorLog.ts, lib/telegram/errors/sendErrorNotification.ts
- Add createErrorLog helper function for error_logs table
- Modify sendErrorNotification to store errors in database
- Maintain 100% backward compatibility with Telegram
- Graceful error handling prevents database failures from breaking notifications
- Extract structured data: account_id, error_type, tool_name, stack_trace
- Store both parsed data and raw telegram message for analysis
=> feat: add Supabase error logging with dual storage

lib/prompts/getSystemPrompt.ts
This reverts commit 445d903fb6dbddd95746810a22dc947cce1bbce5.
=> Revert "Added redis caching in system prompt"

lib/supabase/social_fans/selectSocialFans.ts, lib/tools/getMcpTools.ts, lib/tools/getSocialFans.ts
Add `get_social_fans` tool to retrieve social fan data from Supabase.
---
[Slack Thread](https://voicefirsttech.slack.com/archives/C05QQQS3AH0/p1752270940441569?thread_ts=1752270940.441569&cid=C05QQQS3AH0)
=> Create get social fans tool

app/api/chat/route.ts
Reverts Recoupable-com/Recoup-Chat#940
=> Revert "Limit chat message history to the last 60 messages in POST request ha…"

lib/supabase/artist/updateArtistProfile.tsx
- Changed updateArtistProfile to replace entire knowledges array instead of merging
- Added deduplication by URL to prevent duplicate entries
- Fixes issue where deleted files would reappear after refresh
=> Fix knowledge base deletion not persisting to database

app/files/page.tsx, components/Files/UploadAndList.tsx, hooks/useFilesManager.ts
- Improved the layout of the FilesPage by adjusting padding and adding a title.
- Redesigned the UploadAndList component to include a more user-friendly file upload interface with a button and status messages.
- Updated file upload handling to allow immediate upload upon file selection.
- Enhanced file listing display with better styling and structure.
=> refactor: enhance UploadAndList component and update FilesPage layout

components/Files/UploadAndList.tsx, components/ui/breadcrumb.tsx
- Adjusted padding and margins for improved layout in the UploadAndList component.
- Updated breadcrumb styling for better readability and consistency.
- Increased font sizes and adjusted text alignment for a more polished appearance.
- Enhanced file listing display with refined grid and hover effects.
=> style: enhance UploadAndList component layout and breadcrumb styling

components/Files/FilesGridSkeleton.tsx, components/Files/UploadAndList.tsx
- Introduced a new FilesGridSkeleton component to provide a visual loading state while files are being fetched.
- Replaced the loading text in the UploadAndList component with the FilesGridSkeleton for improved user experience during loading.
=> feat: add FilesGridSkeleton component for loading state in file uploads

components/Files/UploadAndList.tsx, components/Icon/resolver.tsx, utils/getFileVisual.ts
- Integrated getFileVisual utility to determine file icons and colors based on file type and MIME type.
- Updated the UploadAndList component to utilize the new visual representation for files, improving user experience.
- Added audio and video icons to the icon resolver for broader file type support.
=> feat: enhance file visual representation in UploadAndList component

principles.md
- Replace custom markdown parsing with Streamdown for security
- Add custom CSS to maintain exact styling requirements
- Remove unused onQueueUpdate prop following YAGNI principle
- Reorganize Fal utilities from /lib/utils/ to /lib/fal/ for better structure
- Apply Single Responsibility Principle by splitting falConfig.ts
- Remove unnecessary code comments that don't add value
- Update principles.md with new learnings from code review
- Add comprehensive review checklist items for new principles
Security improvements:
- Eliminate dangerouslySetInnerHTML with custom parsing
- Use battle-tested Streamdown library for markdown processing
- Maintain custom styling through CSS overrides
Code organization:
- Create dedicated /lib/fal/ directory for Fal-specific utilities
- Split falConfig.ts …
=> fix: address all code reviewer feedback

app/layout.tsx, components/Files/DownloadMenuItem.tsx, components/Files/FileItemMenu.tsx, components/ui/sonner.tsx, package.json, pnpm-lock.yaml
- Introduced a new DownloadMenuItem component to handle file downloads via signed URLs.
- Integrated the DownloadMenuItem into the FileItemMenu, replacing the previous disabled download option for non-directory files.
- Enhanced user experience by enabling direct file downloads with appropriate filename handling.
=> feat: add DownloadMenuItem component for file downloads

components/Files/FileItemMenu.tsx, components/Files/FilePropertiesPanel.tsx, components/Files/FileTile.tsx, components/Files/FilesGrid.tsx, components/Files/FilesGridList.tsx, components/Files/UploadAndList.tsx, components/Files/types.ts
- Added a new FilePropertiesPanel component to display detailed file information.
- Updated FilesGrid to manage file selection and properties display.
- Refactored FilesGridList and FileTile components for improved file interaction, including properties and delete actions.
- Enhanced FileItemMenu to trigger the properties panel for selected files.
=> feat: implement file properties panel and enhance file grid interaction

components/Files/ArtistAccessSelector.tsx, components/Files/FilePropertiesPanel.tsx, components/ui/separator.tsx, package.json, pnpm-lock.yaml
- Introduced ArtistAccessSelector component to allow users to select and grant access to artists.
- Integrated the new component into the FilePropertiesPanel for enhanced file management.
- Added a Separator component for improved UI layout and organization.
=> feat: add ArtistAccessSelector component for managing artist access

app/api/files/access-artists/route.ts, app/api/files/revoke-access/route.ts, components/Files/ArtistAccessSelector.tsx, components/Files/ArtistAccessSelectorContent.tsx, components/Files/ArtistAccessSelectorSkeleton.tsx, components/Files/ArtistsWithAccess.tsx, components/Files/HasAccessList.tsx, components/Files/RevokeAccessDialog.tsx, components/Files/types.ts, hooks/useFileAccessGrant.tsx, lib/supabase/files/getFileAccessArtists.ts, lib/supabase/files/revokeFileAccess.ts
- Introduced new API routes for retrieving and revoking file access for artists, including validation and error handling.
- Created the `getFileAccessArtists` and `revokeFileAccess` functions to interact with the Supabase database.
- Updated the `ArtistAccessSelector` component to fetch and display artists with access, including loading states and UI improvements.
- Added `ArtistsWithAccess` component to show artists who already have access to a file.
- Enhanced the `useFileAccessGrant` hook to support query invalidation after granting access.
=> feat: add API routes for managing file access and enhance UI components

app/api/files/list/route.ts, components/Files/FileTile.tsx, components/Files/types.ts, hooks/useFilesManager.ts, types/files.ts
- Updated the GET API route to include files granted access to artists, combining them with owned files while ensuring no duplicates.
- Introduced new types for file access results and combined file rows to support the enhanced functionality.
- Enhanced the FileTile component to visually indicate shared files with a subtle overlay, improving user experience.
- Updated related types to accommodate new properties for shared files and access details.
=> feat: enhance file listing and sharing functionality

components/Files/ArtistAccessSelectorContent.tsx
- Integrated useArtistProvider to access the currently selected artist.
- Enhanced filtering logic to exclude the selected artist from the list of available artists for access granting, improving user experience and clarity in artist selection.
=> feat: update ArtistAccessSelectorContent to filter out selected artist

components/Agents/useAgentData.ts
- Updated the useAgentData hook to conditionally enable data fetching based on the presence of userData.id, improving performance and preventing unnecessary requests.
=> feat: enable agent data fetching based on user authentication

components/Agents/AgentCard.tsx
- Eliminated the Lock and Globe icons that indicated agent visibility status.
- Streamlined the AgentCard component for improved clarity and simplicity.
=> refactor: remove visibility icons from AgentCard component

app/api/agent-templates/route.ts, lib/supabase/agent_templates/createAgentTemplate.ts, lib/supabase/agent_templates/deleteAgentTemplate.ts, lib/supabase/agent_templates/listAgentTemplatesForUser.ts, lib/supabase/agent_templates/listAgentTemplatesWithFavourites.ts, lib/supabase/agent_templates/updateAgentTemplate.ts, lib/supabase/agent_templates/verifyAgentTemplateOwner.ts
- Replaced direct Supabase queries in the agent templates route with utility functions for better code organization and maintainability.
- Introduced functions for creating, updating, deleting, and listing agent templates, enhancing modularity.
- Improved error handling and response structure for fetching templates with user favorites.
This refactor streamlines the API logic and prepares the codebase for future enhancements.
=> ✨ Refactor agent template API to use dedicated utility functions

supabase/migrations/20250919000001_fix_agent_templates_complete.sql
- Simple migration that adds curated agents with clear names
- Uses new tag system: Research, Plan, Create, Connect, Report
- Safe approach: no deletions, only additions
- Manual cleanup of old agents can be done via UI
Adds 29 agents:
• Research (8) - Data analysis and insights
• Plan (7) - Strategy and planning
• Create (5) - Content creation
• Connect (6) - Outreach and relationships
• Report (3) - Automated reporting
=> ✨ Add 29 clean agent templates with 5-category system

components/Files/FilesGrid.tsx, components/Files/FilesGridList.tsx, components/Files/UploadAndList.tsx, hooks/useDragAndDrop.ts
- Added `onFilesDropped` prop to `FilesGrid` and `FilesGridList` components to handle dropped files.
- Introduced `useDragAndDrop` hook for managing drag-and-drop interactions, including file validation and error handling.
- Updated `UploadAndList` component to process uploaded files and provide user feedback via toast notifications.
=> feat: implement drag-and-drop file upload functionality

lib/supabase/files/findFileByName.ts, lib/tools/files/index.ts, lib/tools/files/readFile.ts, lib/tools/getMcpTools.ts
- Introduced `findFileByName` function to locate files in the artist's storage directory.
- Added `readFile` tool to read file content and handle errors gracefully.
- Created `listFiles` and `readFile` exports in the files module for better file management.
- Updated `getMcpTools` to include new file tools for enhanced functionality.
=> feat: add file management tools for reading and listing files

lib/supabase/files/createFileRecord.ts, lib/supabase/files/ensureDirectoryExists.ts, lib/tools/files/index.ts, lib/tools/files/writeFile.ts
- Introduced `createFileRecord` function to handle file metadata storage in the database.
- Added `writeFile` tool for creating new files in storage, including content validation and MIME type detection.
- Updated `filesTools` module to include the new `writeFile` functionality, enhancing file management capabilities.
=> feat: add file management tools for creating and writing files

lib/tools/files/index.ts, lib/tools/files/updateFile.ts
- Introduced `updateFile` tool to allow users to modify the content of existing files in storage.
- Updated `filesTools` module to include the new `updateFile` functionality, enhancing file management capabilities.
- Implemented input validation and error handling for file updates, ensuring robust functionality.
=> feat: add updateFile tool for modifying existing files
