components/Funnels/AnalysisButton.tsx

- actual: AnalysisButton - onClick is throwing an error
- required: AnalysisButton - onClick should trigger socket connection to the Recoup API to start the initial tavily agent
- reference: components/Funnels/AnalysisButton.tsx
- ERROR
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'replaceAll')
Source
hooks/useAgentSocket.tsx (62:40) @ replaceAll
60 |       funnels.map((funnel) => {
61 |         socketIo.emit(`${funnel.toUpperCase()}_ANALYSIS`, socketId, {
> 62 |           handle: handles[`${funnel}`].replaceAll("@", "") || "",
|                                        ^
63 |           pilot_id: chatId,
64 |           account_id: userData?.account_id,
65 |           address,
```

Wrapped Funnel - AnalysisButton - onClick Debug

---

.cursorrules
hooks/useChatContext.tsx
hooks/useMessages.tsx
lib/chat/getSystemMessage.tsx

actual:
The current implementation of useChatContext includes a hard-coded useEffect that adds comments to the chat context.
required:
Remove the hard-coded useEffect so that comments are never added to the chat context. The useChatContext should only contain a JSON object with { activeArtist: selectedArtist }, ensuring that no comments are included in the context.

P1: useChatContext - remove hard-coded useEffect for comments context

---

types/database.types.ts

This PR updates the database.types.ts file to reflect recent schema changes:
- Moved artist_id field from the memories table to the rooms table
- Added foreign key relationship for artist_id in the rooms table
- Includes the new sales_pipeline_customers table that was added to the database from the founders dashboard repo
**The types were regenerated using the Supabase CLI to ensure they match the current database schema.**

MYC-1299: Update database.types.ts to reflect artist_id moved from memories to rooms table

---

app/api/chat/route.ts
app/api/memories/create/route.ts
app/api/room/get/route.tsx
hooks/useConversations.tsx
hooks/useMessages.tsx
lib/createMemory.tsx
lib/supabase/createMemories.tsx
types/Chat.tsx

This PR updates code references to reflect the database schema change where the `artist_id` field was moved from the `memories` table to the `rooms` table.
Changes:
- Removed `artist_id` from memory creation and storage
- Updated API routes to no longer use `memories.artist_id`
- Updated the conversation filtering logic to use `rooms.artist_id`
- Updated type definitions to reflect the schema change
This PR depends on the database migration that was already applied (MYC-1299).

MYC-1264: Update references to memories.artist_id to use rooms.artist_id

---

app/api/room/create/route.tsx
app/segment/[segmentId]/page.tsx
hooks/useChat.tsx
lib/createRoom.tsx
lib/supabase/createRoomWithReport.ts

This PR updates the room creation logic to work with the new database structure where artist_id is in the rooms table. This enables all new chats to work correctly with the updated database schema.
**Changes:**
- Updated `createRoom` function to accept an `artist_id` parameter
- Updated room creation API to accept `artist_id` as a query parameter
- Updated `createRoomWithReport` function to include `artist_id` in the database insert
- Updated `useChat` hook to pass the selected artist's account_id as the `artist_id`
- Updated segment page to include the `artist_id` parameter in the `createRoomWithReport` call
This PR depends on the database migration that was already applied (MYC-1299).

MYC-1265: Migrate room creation to use rooms.artist_id

---

app/autopilot/page.tsx
app/page.tsx
components/SideMenu/SideMenu.tsx
components/Sidebar/Menu.tsx
components/Sidebar/MiniMenu.tsx
hooks/usePrompts.tsx

This PR changes the root route (/) to display the chat interface instead of Autopilot, creating a more intuitive user experience.
Changes:
- Changed root route (/) to display the chat interface instead of Autopilot
- Created new route (/autopilot) for the Autopilot functionality
- Updated all navigation components to point to the new routes
- Fixed suggestion boxes to appear correctly on the root path
This change improves the user experience by making the chat interface the default page while keeping the Autopilot functionality accessible through a dedicated route.

MYC-1304: Change Root Route to Initial Chat Interface

---

app/page.tsx
components/AutoPilot/AutoPilot.tsx
hooks/useAutoLogin.tsx
hooks/useLoginRedirect.tsx

Created a reusable `useLoginRedirect` hook that centralizes login logic and applied it to the root page.
- Improves code organization by extracting login logic from the AutoPilot component
- Follows DRY principles by reusing the same login logic across multiple pages
- Ensures users are prompted to login when landing on the root page
- Makes future login-related changes easier to maintain
- Verified that users not signed in are prompted to login when landing on the root page
- Confirmed existing login functionality in AutoPilot page continues to work as expected

MYC-1317: Move login logic to root page following DRY principles

---

components/Funnels/SegmentButton.tsx

**Problem**
Segment cards appeared on top of sidebars on mobile.
**Solution**
Removed z-20 class from SegmentButton component.
**Changes**
Single-line change in components/Funnels/SegmentButton.tsx
**Testing**
Verified on mobile - segment cards now stay behind sidebars.

MYC-1318: Fix mobile sidebar z-index bug by removing z-20 class from SegmentButton

---

hooks/usePrompts.tsx

When creating a new chat with a non-default artist selected (e.g., Chillpill), the app would automatically switch back to the first artist in the list. This happened because `usePrompts.tsx` had logic that would automatically select the first artist when no artist was selected, but this logic was triggering incorrectly during chat creation.
Modified `usePrompts.tsx` to:
- Remove the auto-selection of first artist
- Remove `artists` and `setSelectedArtist` from the hook
- Keep the user's explicitly selected artist
- Single file change: `hooks/usePrompts.tsx`
- Removed 7 lines, added 2 lines
- No new dependencies added
- No database changes required
To verify this fix:
1. Select a non-default artist (e.g., Chillpill)
2. Create a new chat via /new (not via root) [separate ticket fixes root …

MYC-1328: Stop automatic artist switching during chat creation

---

hooks/useMessages.tsx

Messages from previous chats were appearing in newly created chats.
1. Open any existing chat and view messages
2. Click "New Chat"
3. Type and submit a message in the new chat (e.g., "Test message")
4. Bug: After submission, messages from the previous chat incorrectly appear along with your new message
5. Note: This only happens during new chat creation, not when navigating between existing chats
- Added chat-specific isolation using AI SDK's `id` prop in `useMessages` hook
- Added cleanup effect for new chat creation
- Minimal solution that leverages existing architecture
1. Create Chat One:
- Click "New Chat"
- Send a message: "This is Chat One"
- Verify only this message appears
2. Create Chat Two:
- Navigate to Chat One first
- Click "New Chat"
- Send a message: "This is Chat Two"
- …

MYC-1355: prevent messages from displaying in wrong rooms 

---

hooks/useChat.tsx

Problem
The chat input field was not clearing after message submission, causing confusion for users who had to manually clear the field before typing a new message.
Solution
Modified the handleSubmit function in the useChat hook to reset the input field after a message is successfully submitted:
Added handleInputChange to the destructured imports from useMessagesProvider
Added a line to reset the input field by calling handleInputChange with an empty string after the message is appended
Testing
Manually verified that:
The input field now clears properly after sending a message
The message submission process works as expected
No side effects were introduced by this change

MYC-1356: clear input field after message submission

---

app/instant/[roomId]/page.tsx
components/VercelChat/chat.tsx
components/VercelChat/messages.tsx

actual: The /instant/[chatID] route does not display HTML room reports that are available in the /[chatID] route.
required:
Implement HTML room report display functionality in the /instant/[chatID] route
Reference the implementation in /[chatID] route as the pattern to follow
Ensure visual and functional parity of room reports between both routes
Maintain all existing functionality of the /instant/[chatID] route

P1: Add Room Report HTML Support to /instant/[chatID] Route

---

app/layout.tsx
components/ArtistSelectionOverlay.tsx
components/Artists/ArtistsSidebar.tsx
components/Chat/ChatGreeting.tsx
components/Chat/ChatPrompt.tsx
components/Header/Artist.tsx
components/Header/Header.tsx
components/ImageWithFallback.tsx
components/SideArtists/SideArtists.tsx
components/SideMenu/SideMenu.tsx
components/SideModal/SideModal.tsx
components/VercelChat/ChatInput.tsx
components/VercelChat/chat.tsx
components/VercelChat/input.tsx
components/common/ArtistButton.tsx
components/common/ArtistTooltip.tsx
hooks/useArtistSelection.ts
providers/Providers.tsx
providers/SidebarExpansionContext.tsx
tailwind.config.ts
utils/artistHelpers.ts
utils/tooltipPositioning.ts

Addresses P0 issue where manually onboarded users could chat without selecting an artist, leading to poor user experience and confusion.
Added two key improvements to guide users to select an artist before chatting:
- Added tooltips that appear when no artist is selected
- Tooltips guide users through the artist selection process
- Clear visual indicators show users where to click
- Tooltips automatically disappear after artist selection
- Improved artist selection sidebar on mobile
- Made artist names clearly visible in mobile view
- Added dim overlay for better focus during selection
- Ensured consistent right-side opening behavior
Please verify:
1. New User Flow:
- User sees tooltips when opening app without artist selected
- Clear guidance directs user to artist selection
- System …

myc-1661-p0-manual-onboarding-users-lets-them-chat-without-artist

---

.cursor/rules/scratchpad.mdc
supabase/migrations/20250621183810_create_error_logs_table.sql

A new Supabase migration file, `supabase/migrations/20250621183810_create_error_logs_table.sql`, was created to define the `error_logs` table.
*   The table schema, including columns such as `id`, `account_id`, `room_id`, `error_message`, `raw_message` (required), and `created_at`, was derived from the `error_logs` definition found in `types/database.types.ts`.
*   Foreign key constraints were established for `account_id` referencing `accounts(id)` and `room_id` referencing `rooms(id)`.
*   Row Level Security was enabled, and appropriate permissions were granted to `anon`, `authenticated`, and `service_role` roles. An `updated_at` trigger was also added.
*   These structural and security elements were implemented by referencing patterns found in existing migration files within the …

Create migration for error-logs table

---

components/Agents/AgentCard.tsx
components/Agents/Agents.tsx
components/Agents/useAgentData.ts
components/Chat/StarterAgentCard.tsx
components/Chat/StarterAgents.tsx

Major improvements to agent cards:
- Create separate StarterAgentCard component for initial chat vs agents tab
- Redesign AgentCard with grey background matching sidebar aesthetic
- Implement consistent card heights (h-44) for clean grid layout
- Update action tag system with multi-word names and proper filtering
- Add responsive design preventing description cut-offs on mobile
- Streamline visual design - reduced padding, lighter typography
- Improve action pills with proper rounded styling and borders
- Better grid spacing and layout for less intimidating appearance
- Filter action tags from top navigation (Deep Research, Send Report, etc.)
- Maintain white/black/grey minimal color scheme throughout

feat: redesign agent cards with separate components and improved UX

---

components/VercelChat/ToolComponents.tsx
components/VercelChat/tools/DeleteScheduledActionsSkeleton.tsx

A new React component, `DeleteScheduledActionsSkeleton`, was created in `components/VercelChat/tools/DeleteScheduledActionsSkeleton.tsx`.
This component provides a UI skeleton for the `delete_scheduled_actions` tool's pending state.
It features a red-themed design, consistent with deletion operations, and includes `Trash2` and `Clock` icons within animated skeleton cards to simulate loading.
The `components/VercelChat/ToolComponents.tsx` file was modified to integrate this new skeleton.
An import statement for `DeleteScheduledActionsSkeleton` was added.
Additionally, a new case was introduced within the `getToolCallComponent` function to render `DeleteScheduledActionsSkeleton` when the `toolName` is `delete_scheduled_actions`.
These changes ensure that a dedicated, visually consistent …

Create tool result UI skeleton component

---

supabase/migrations/20250703000000_youtube_tokens_row_level_security.sql

Add RLS to `youtube_tokens` table to restrict access to server keys only.

Implement row-level security for youtube_tokens

---

hooks/useVercelChat.ts
lib/chat/setupChatRequest.ts

- Updated useVercelChat hook to retrieve email from user provider
- Modified setupChatRequest function to directly accept email from the request body
- Removed redundant email fetching logic from setupChatRequest

Refactor chat setup to include email in request body and user data

---

supabase/migrations/20250916130500_create_file_access_table.sql

- Introduced a new table "file_access" to store access grants for files, including fields for user and organization IDs, access scope, and timestamps for expiration and revocation.
- Added foreign key constraints to link with existing "files" and "accounts" tables.
- Implemented row-level security and various indexes to optimize access queries.
- Defined access grants for different user roles: anon, authenticated, and service_role.

feat: create file_access table for managing per-file access grants

---

components/Files/FilePropertiesPanel.tsx

- Added a Badge component to visually indicate when a file is shared within the FilePropertiesPanel.
- Updated the FileMeta type to include an is_shared property for better file metadata management.
- Adjusted the rendering logic to conditionally display the Badge based on the is_shared status of the file.

feat: enhance FilePropertiesPanel with shared file indication

---

supabase/migrations/20250917173709_add_created_at_to_agent_templates.sql

- Introduced a new column 'created_at' to the agent_templates table to track creation timestamps.
- The column is set to NOT NULL with a default value of the current timestamp.

feat: add created_at column to agent_templates table

---

components/Agents/Agents.tsx
components/Agents/useAgentData.ts

- Introduced a switch to toggle between public and private agent visibility in the Agents component.
- Updated the useAgentData hook to manage the private state and filter agents accordingly.

feat: add toggle for agent visibility between public and private

---

components/VercelChat/ChatInput.tsx

- Change from default 'border' to 'border-gray-200'
- Makes chat input boundary slightly more visible
- Subtle improvement without changing overall design

🎨 Improve chat input border visibility

---

supabase/migrations/20250919141957_create_agent_template_shares.sql

- Create a new table `agent_template_shares` to allow users to share agent templates with others
- Implement foreign key references to `agent_templates` and `accounts`
- Add indexes for improved query performance
- Enable row level security and grant necessary permissions for authenticated and anonymous users

✨ Add agent template shares table for user sharing functionality

---

app/api/agent-templates/route.ts
lib/supabase/accountEmails/getAccountDetailsByEmails.ts
lib/supabase/agent_templates/createAgentTemplate.ts
lib/supabase/agent_templates/createAgentTemplateShares.ts
lib/supabase/agent_templates/deleteAgentTemplateShares.ts
lib/supabase/agent_templates/insertAgentTemplateShares.ts
lib/supabase/agent_templates/updateAgentTemplate.ts
lib/supabase/agent_templates/updateAgentTemplateShares.ts

- Added `shareEmails` parameter to the agent template creation and update processes.
- Enhanced `createAgentTemplate` and `updateAgentTemplate` functions to handle email sharing.
- Introduced helper functions to manage the creation and updating of agent template shares in the database.
- Updated API routes to accommodate the new sharing feature, ensuring proper handling of private templates.

✨ Implement email sharing functionality for agent templates

---

components/ModelSelect/ModelSelect.tsx

- Remove nested PromptInputModelSelect that was causing conflicts
- Convert 'More Models' from nested dropdown to simple section header
- All models now use single Select context with proper value handling
- Fixes issue where clicking models in expanded menu did nothing
Now clicking any model in the 'More Models' section properly selects it.

🔧 Fix model selection in 'More Models' dropdown

---

lib/chat/generateChatTitle.ts

- Modified the prompt to specify that the title should not be wrapped in quotes.
- Added a safeguard to remove any accidental quotes from the generated title before returning it.

Update chat title generation to prevent quotes in output

---

components/Files/FileTile.tsx

- Integrated the PhotoView component to allow for a better image viewing experience.
- Wrapped the image element in PhotoView to enable full-screen viewing capabilities.

Add PhotoView component to FileTile for enhanced image viewing
